<?php
// $Id: xoops_version.php,v 1.17 2006/04/08 08:18:49 nao-pon Exp $

$pwm_dirname = basename( dirname( __FILE__ ) ) ;
if( preg_match( '/^(\D+)(\d*)$/' , $pwm_dirname , $regs ) ) {
	$pwm_number = $regs[2] ;
} else {
	echo ( "invalid dirname: " . htmlspecialchars( $pwm_dirname ) ) ;
}

$modversion['name'] = "PukiWiki";
$modversion['description'] = "PukiWiki";
$modversion['credits'] = "";
$modversion['author'] = "";
$modversion['help'] = "";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "pukiwiki.gif";
$modversion['dirname'] = $pwm_dirname;
include_once(XOOPS_ROOT_PATH."/modules/".$modversion['dirname']."/version.php");
$modversion['version'] = _XOOPS_WIKI_VERSION;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql{$pwm_number}.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "pukiwikimod{$pwm_number}_count";
$modversion['tables'][1] = "pukiwikimod{$pwm_number}_pginfo";
$modversion['tables'][2] = "pukiwikimod{$pwm_number}_plain";
$modversion['tables'][3] = "pukiwikimod{$pwm_number}_tb";
$modversion['tables'][4] = "pukiwikimod{$pwm_number}_attach";
$modversion['tables'][5] = "pukiwikimod{$pwm_number}_rel";

//Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Menu
global $xoopsUser;
$wiki_allow_new = 0;
@include(XOOPS_ROOT_PATH."/modules/".$modversion['dirname']."/cache/config.php");

$modversion['hasMain'] = 1;
$modversion['sub'][0]['name'] = _MI_PUKIWIKI_RECENT;
$modversion['sub'][0]['url'] = "?RecentChanges";
$modversion['sub'][1]['name'] = _MI_PUKIWIKI_LIST;
$modversion['sub'][1]['url'] = "?cmd=list";
if (!$wiki_allow_new || ($wiki_allow_new == 1 && is_object($xoopsUser)))
{
	$modversion['sub'][2]['name'] = _MI_PUKIWIKI_NEWPAGE;
	$modversion['sub'][2]['url'] = "?plugin=newpage";
}

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "xoops_search.inc.php";
$modversion['search']['func'] = "wiki{$pwm_number}_search";

// Blocks
$modversion['blocks'][1]['file'] = "pukiwiki_new.php";
$modversion['blocks'][1]['name'] = _MI_PUKIWIKI_BNAME1;
$modversion['blocks'][1]['description'] = "Shows recently contents";
$modversion['blocks'][1]['show_func'] = "b_pukiwiki_new_show";
$modversion['blocks'][1]['edit_func'] = "b_pukiwiki_new_edit";
$modversion['blocks'][1]['options'] = "{$pwm_dirname}";
$modversion['blocks'][1]['can_clone'] = true ;
$modversion['blocks'][1]['template'] = '';

$modversion['blocks'][2]['file'] = "pukiwiki_page.php";
$modversion['blocks'][2]['name'] = "PukiWiki Page#1";
$modversion['blocks'][2]['description'] = "Show A PukiWiki's page.";
$modversion['blocks'][2]['show_func'] = "b_pukiwiki_page_show";
$modversion['blocks'][2]['edit_func'] = "b_pukiwiki_page_edit";
$modversion['blocks'][2]['options'] = "|5|1|{$pwm_dirname}";
$modversion['blocks'][2]['can_clone'] = true ;
$modversion['blocks'][2]['template'] = '';

$modversion['blocks'][3]['file'] = "pukiwiki_page.php";
$modversion['blocks'][3]['name'] = "PukiWiki Page#2";
$modversion['blocks'][3]['description'] = "Show A PukiWiki's page.";
$modversion['blocks'][3]['show_func'] = "b_pukiwiki_page_show";
$modversion['blocks'][3]['edit_func'] = "b_pukiwiki_page_edit";
$modversion['blocks'][3]['options'] = "|5|2|{$pwm_dirname}";
$modversion['blocks'][3]['template'] = '';

$modversion['blocks'][4]['file'] = "pukiwiki_page.php";
$modversion['blocks'][4]['name'] = "PukiWiki Page#3";
$modversion['blocks'][4]['description'] = "Show A PukiWiki's page.";
$modversion['blocks'][4]['show_func'] = "b_pukiwiki_page_show";
$modversion['blocks'][4]['edit_func'] = "b_pukiwiki_page_edit";
$modversion['blocks'][4]['options'] = "|5|3|{$pwm_dirname}";
$modversion['blocks'][4]['template'] = '';

$modversion['blocks'][5]['file'] = "pukiwiki_new.php";
$modversion['blocks'][5]['name'] = _MI_PUKIWIKI_BNAME2;
$modversion['blocks'][5]['description'] = "Shows recently TrackBack.";
$modversion['blocks'][5]['show_func'] = "b_pukiwiki_newtb_show";
$modversion['blocks'][5]['edit_func'] = "b_pukiwiki_new_edit";
$modversion['blocks'][5]['options'] = "{$pwm_dirname}";
$modversion['blocks'][5]['can_clone'] = true ;
$modversion['blocks'][5]['template'] = '';

$modversion['blocks'][6]['file'] = "pukiwiki_new.php";
$modversion['blocks'][6]['name'] = _MI_PUKIWIKI_BNAME3;
$modversion['blocks'][6]['description'] = "Shows recently attached files.";
$modversion['blocks'][6]['show_func'] = "b_pukiwiki_newattach_show";
$modversion['blocks'][6]['edit_func'] = "b_pukiwiki_new_edit";
$modversion['blocks'][6]['options'] = "{$pwm_dirname}";
$modversion['blocks'][6]['can_clone'] = true ;
$modversion['blocks'][6]['template'] = '';

// Templates
$modversion['templates'][1]['file'] = "pukiwikimod{$pwm_number}_index.html";
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = "pukiwikimod{$pwm_number}_comments.html";
$modversion['templates'][2]['description'] = '';

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'index.php';
$modversion['comments']['itemName'] = 'pgid';
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
//$modversion['comments']['callback']['approve'] = 'pukiwiki_com_approve';
$modversion['comments']['callback']['update'] = 'pukiwiki_com_update';

// On Update
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] ) {
	include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
}

?>